




.build/mega2560/src/ethernetShield.cpp : src/ethernetShield.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/ethernetShield.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/ethernetShield.cpp
	@true

